apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: shadowmail
  name: shadowmail-flask
  labels:
    app: shadowmail
    component: flask
spec:
  secretName: shadowmail-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.${DOMAIN_NAME}
  dnsNames:
  - ${DOMAIN_NAME}
  - www.${DOMAIN_NAME}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ${DOMAIN_NAME}
      - www.${DOMAIN_NAME}
