apiVersion: v1
kind: ConfigMap
metadata:
  name: shadowmail-config
  namespace: shadowmail
data:
  DB_DOMAIN: "${DB_DOMAIN}"
  FLASK_APP: "/app/main.py"
  APP_SETTINGS: "Docker" 
  DB_PROTOCOL: postgres
