version: '2'
services:
  db:
    build: ./mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'shadowmail'
      FLASK_DB_PASSWORD: ${FLASK_DB_PASSWORD}
      POSTFIX_DB_PASSWORD: ${POSTFIX_DB_PASSWORD}
    volumes:
      - /var/log/mysql:/var/log/mysql
      - /var/lib/mysql:/var/lib/mysql

  postfix:
    build: ./postfix
    environment:
      DB_USERNAME: postfix
      DB_PASSWORD: ${POSTFIX_DB_PASSWORD}
      DB_HOSTS: db:3306

      # Inherited from tozd/postfix
      MAILNAME: ${MAILNAME}
      MY_NETWORKS: 172.18.0.0/16 127.0.0.0/8
      MY_DESTINATION: $$myhostname, ${MAILNAME}, localhost.localdomain, localhost
      ROOT_ALIAS: ""
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    depends_on:
      - db
    volumes:
      - /var/log/postfix:/var/log/postfix
      - /var/spool/postfix:/var/spool/postfix
      - ${SSL_LOCATION}:/ssl:ro

  flask:
    build: ./flask
    ports:
      - "80:80"
    environment:
      APP_SETTINGS: 'Docker'
      DB_PASSWORD: ${FLASK_DB_PASSWORD}
      SECRET_KEY: ${FLASK_SECRET_KEY}
    depends_on:
      - db
    volumes:
      - /var/log/nginx:/var/log/nginx
