version: '3.4'
services:
  db:
    image: postgres:12.3
    environment:
      POSTGRES_DATABASE: 'shadowmail'
      POSTGRES_USER: 'shadowmail'
      POSTGRES_PASSWORD: 'shadowmail_pass'
    volumes:
    - /var/lib/postgresql/data

  proxy:
    image: nginx:latest
    depends_on:
    - frontend
    - backend
    ports:
    - 8000:80
    volumes:
    - ./nginx_proxy.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: "none"

  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
    - ./frontend:/app
    - /app/node_modules/

  backend:
    build: ./flask
    depends_on:
    - db
    environment:
      APP_SETTINGS: 'Development'
      DB_USERNAME: 'shadowmail'
      DB_PASSWORD: 'shadowmail_pass'
      SECRET_KEY: 'SECRET_KEY'
      DB_DOMAIN: 'db'
      DB_PROTOCOL: 'postgres'
      RELOAD: '--reload'
      FLASK_APP: '/app/main.py'
    volumes:
    - ./flask/app:/app:ro

  migrate:
    build: ./flask
    depends_on:
    - db
    environment:
      APP_SETTINGS: 'Development'
      DB_USERNAME: 'shadowmail'
      DB_PASSWORD: 'shadowmail_pass'
      DB_DOMAIN: 'db'
      DB_PROTOCOL: 'postgres'
      FLASK_APP: '/app/main.py'
    restart: on-failure
    command: flask initdb

  postfix:
    build: ./postfix
    environment:
      DB_USERNAME: 'shadowmail'
      DB_PASSWORD: 'shadowmail_pass'
      # DB_HOSTS: db:5432
      DB_HOSTS: 172.23.0.2:5432 # TODO this DNS lookup fails.  Using IP instead

      # AWS SES
      AWS_SMTP_USERNAME: ${AWS_SMTP_USERNAME}
      AWS_SMTP_PASSWORD: ${AWS_SMTP_PASSWORD}

      # Inherited from tozd/postfix
      MAILNAME: ${MAILNAME}
      MY_NETWORKS: 172.18.0.0/16 127.0.0.0/8
      MY_DESTINATION: $$myhostname, ${MAILNAME}, localhost.localdomain, localhost
      ROOT_ALIAS: ""
    ports:
      - "25:25"
      - 465:465
      - 587:587
    depends_on:
      - db
    volumes:
      - ./postfix/test_certs:/ssl:ro
      - ./postfix/etc/postfix/main.cf:/etc/postfix/main.cf
      - ./postfix/etc/postfix/master.cf:/etc/postfix/master.cf
      - ./postfix/etc/postfix/pgsql-aliases.cf:/etc/postfix/pgsql-aliases.cf
      - ./postfix/etc/service:/etc/service:ro
      - ./postfix/scripts:/scripts:ro
      - ./postfix/entrypoint.sh:/entrypoint.sh:ro
