version: '2'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: 'shadowmail'
      POSTGRES_USER: 'shadowmail'
      POSTGRES_PASSWORD: 'shadowmail_pass'
    volumes:
    - ./build/database:/var/lib/postgresql/data

  proxy:
    image: nginx:latest
    depends_on:
      - frontend
      - backend
    ports:
    - 8000:80
    volumes:
    - ./nginx_proxy.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: "none"

  frontend:
    build: ./frontend
    environment:
      COMMAND: 'develop'
    volumes:
    - ./frontend/src:/app/src
    - ./frontend/gatsby-browser.js:/app/gatsby-browser.js
    - ./frontend/gatsby-config.js:/app/gatsby-config.js

  backend:
    build: ./flask
    environment:
      APP_SETTINGS: 'Development'
      DB_USERNAME: 'shadowmail'
      DB_PASSWORD: 'shadowmail_pass'
      SECRET_KEY: 'SECRET_KEY'
      DB_DOMAIN: 'db'
      DB_PROTOCOL: 'postgres'
      RELOAD: '--reload'
    volumes:
    - ./flask/app:/app:ro

  migrate:
    build: ./flask
    depends_on:
    - db
    environment:
      APP_SETTINGS: 'Development'
      DB_USERNAME: 'shadowmail'
      DB_PASSWORD: 'shadowmail_pass'
      DB_DOMAIN: 'db'
      DB_PROTOCOL: 'postgres'
      FLASK_APP: '/app/main.py'
    restart: on-failure
    command: flask initdb

  # postfix:
  #   build: ./postfix
  #   environment:
  #     DB_USERNAME: postfix
  #     DB_PASSWORD: ${POSTFIX_DB_PASSWORD}
  #     DB_HOSTS: db:3306

  #     # Inherited from tozd/postfix
  #     MAILNAME: ${MAILNAME}
  #     MY_NETWORKS: 172.18.0.0/16 127.0.0.0/8
  #     MY_DESTINATION: $$myhostname, ${MAILNAME}, localhost.localdomain, localhost
  #     ROOT_ALIAS: ""
  #   ports:
  #     - "25:25"
  #     - "465:465"
  #     - "587:587"
  #   depends_on:
  #     - db
  #   volumes:
  #     - /var/log/postfix:/var/log/postfix
  #     - /var/spool/postfix:/var/spool/postfix
  #     - ${SSL_LOCATION}:/ssl:ro
