#!/bin/bash -e

# Taken from https://github.com/tozd/docker-postfix/

# A stale PID file can prevent rsyslogd from running.
rm -f /var/run/rsyslogd.pid

mkdir -p /var/log/postfix
chown syslog:syslog /var/log/postfix

exec /usr/sbin/rsyslogd -n -c5 2>&1
