name: Test

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches-ignore:
      - 'master'

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build ./flask --file ./flask/Dockerfile -t flask
    - name: Run tests
      run: docker run -e APP_SETTINGS=Testing --entrypoint bash flask make ci

  test_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build ./frontend --file ./frontend/Dockerfile -t frontend --target development
    - name: Run tests
      run: docker run --entrypoint bash frontend make ci

  test_postfix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build ./postfix --file ./postfix/Dockerfile -t postfix
    - name: Run tests
      run: docker run --entrypoint bash postfix make ci
