name: Test

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches-ignore:
      - 'master'

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install and test
      env:
        APP_SETTINGS: 'Testing'
        FLASK_APP: ./main.py
      run: |
        cd flask/
        make install
        pip install pylint pytest
        make test

  test_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install and test
      run: |
        cd frontend/
        make install
        make test

  test_postfix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install and test
      run: |
        cd postfix/
        make install
        make test
